# Generated by Django 4.2.6 on 2023-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default=44, upload_to='images'),
            preserve_default=False,
        ),
    ]
